# Problem Statement : Hospital Patient Data Analysis

In [1]:
import pandas as pd

df_patient = pd.read_csv("Patient_Data.csv")
df_billing = pd.read_csv("Billing_Data.csv")
df_patient.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 464.0+ bytes

In [2]:
new_df_patient = df_patient.drop(labels=['ReceptionistID','CheckInTime'],axis=1)
new_df_patient

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN
5        101    Alice   Cardiology  Dr. Smith      5000.0

In [3]:
total_bill_amount_per_department = new_df_patient.groupby('Department')['BillAmount'].sum()
total_bill_amount_per_department

Department
Cardiology     16200.0
Dermatology        0.0
Neurology          0.0
Orthopedics     7500.0
Name: BillAmount, dtype: float64

In [4]:
cleaned_patient_data = df_patient.drop_duplicates(subset='PatientID')
cleaned_patient_data

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45

In [5]:
cleaned_patient_data = cleaned_patient_data.copy()
cleaned_patient_data['BillAmount'] = cleaned_patient_data['BillAmount'].fillna(cleaned_patient_data['BillAmount'].mean())
cleaned_patient_data['BillAmount']

0    5000.000000
1    6233.333333
2    7500.000000
3    6200.000000
4    6233.333333
Name: BillAmount, dtype: float64

In [6]:
df_merged = pd.merge(cleaned_patient_data, df_billing, on='PatientID')
df_merged

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,1,2023-01-10 09:00,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,2,2023-01-11 10:30,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,1,2023-01-12 11:00,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3,2023-01-13 12:00,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,2,2023-01-14 08:45,1000,4000

In [7]:
df_new_patients = pd.DataFrame({
    'PatientID': [106, 107],
    'Name': ['Fiona', 'George'],
    'Department': ['Cardiology', 'Neurology'],
    'Doctor': ['Dr. Smith', 'Dr. John'],
    'BillAmount': [6800, 7200],
    'ReceptionistID': [2, 3],
    'CheckInTime': ['2023-01-15 10:00', '2023-01-16 11:30']
})

df_updated = pd.concat([cleaned_patient_data, df_new_patients], axis=0, ignore_index=True)
df_updated

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.000000,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,6233.333333,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.000000,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,6233.333333,2,2023-01-14 08:45
5,106,Fiona,Cardiology,Dr. Smith,6800.000000,2,2023-01-15 10:00
6,107,George,Neurology,Dr. John,7200.000000,3,2023-01-16 11:30

In [8]:
df_new_cols = pd.DataFrame({
    'InsuranceCovered': [2000, 1500, 3000, 2500, 1800, 1200, 1345],
    'FinalAmount': [3000, 4425, 4500, 3700, 4125, 1890, 2300]
})
df_updated = df_updated.drop(columns=['InsuranceCovered', 'FinalAmount'], errors='ignore')

df_updated_new_columns = pd.concat([df_updated, df_new_cols], axis=1)
df_updated_new_columns

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,1,2023-01-10 09:00,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,2,2023-01-11 10:30,1500,4425
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,1,2023-01-12 11:00,3000,4500
3,104,David,Cardiology,Dr. Smith,6200.000000,3,2023-01-13 12:00,2500,3700
4,105,Eva,Dermatology,Dr. Rose,6233.333333,2,2023-01-14 08:45,1800,4125
5,106,Fiona,Cardiology,Dr. Smith,6800.000000,2,2023-01-15 10:00,1200,1890
6,107,George,Neurology,Dr. John,7200.000000,3,2023-01-16 11:30,1345,2300

# Expected Outcomes

No duplicate columns

BillAmount missing values handled (mean = 5925)

New patients included

Billing columns (InsuranceCovered, FinalAmount) present

Dataset looks consistent and usable

No NaNs visible in final output

Department wise Revenue

In [10]:
df_updated_new_columns.groupby('Department')['FinalAmount'].sum()

Department
Cardiology     8590
Dermatology    4125
Neurology      6725
Orthopedics    4500
Name: FinalAmount, dtype: int64

Doctor's Performance

In [11]:
df_updated_new_columns.groupby('Doctor')['FinalAmount'].sum()

Doctor
Dr. John     6725
Dr. Lee      4500
Dr. Rose     4125
Dr. Smith    8590
Name: FinalAmount, dtype: int64

Average Billing per Department

In [13]:
df_updated_new_columns.groupby('Department')['BillAmount'].mean()

Department
Cardiology     6000.000000
Dermatology    6233.333333
Neurology      6716.666667
Orthopedics    7500.000000
Name: BillAmount, dtype: float64